### PR TITLE
fix issue 5 (uri with null bytes (e.g. %00) were crashing the Static middleware)

### PR DESCRIPTION
**Pull request by grepsuzette**
Fixing #5 

Cutting string at the first encountered null byte  and  removing null bytes both seem very dubious.
So I went with Static middleware ignoring any uri with a path containing a null byte.

### CODE REVIEW

**Comment by back2dos** [comment]
I think it's ok, but I wonder if there's perhaps a better "global" strategy we can adopt for dealing with null bytes. If the middleware passes, then it's still quite likely to crash later.

**Comment by grepsuzette** [comment]
Since today `tink_url` commit fixes the invalid url problem for the router but not for middlewares 
I pushed another commit to catch exceptions from the `urlDecode()`.

**Comment by back2dos** [comment]
Thanks ;)

**Comment by kevinresol** [comment]
Great work, I love the quality of this PR :)

**Pull request merged**
